services:
  db:
    image: postgres:16-alpine
    container_name: collegebuddy-db
    environment:
      POSTGRES_DB: collegebuddy
      POSTGRES_USER: collegebuddy
      POSTGRES_PASSWORD: collegebuddy
    ports:
      - "5432:5432"            # change left side to 5433 if host 5432 is busy
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./docker/init:/docker-entrypoint-initdb.d  # optional init scripts
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U collegebuddy -d collegebuddy -h localhost -p 5432"]
      interval: 5s
      timeout: 3s
      retries: 20
    restart: unless-stopped


  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    container_name: collegebuddy-infra
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/collegebuddy
      SPRING_DATASOURCE_USERNAME: collegebuddy
      SPRING_DATASOURCE_PASSWORD: collegebuddy
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_FLYWAY_ENABLED: "true"
      JWT_SECRET: "change-me-in-prod-32bytes-min-change-me-in-prod"
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  dbdata:
