server:
  port: 8080

spring:
  datasource:
    # Default to the Docker service host ("db") in prod, not localhost.
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://db:5432/collegebuddy}
    username: ${SPRING_DATASOURCE_USERNAME:collegebuddy}
    password: ${SPRING_DATASOURCE_PASSWORD:collegebuddy}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
      minimum-idle: 2
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc.lob.non_contextual_creation: true
        format_sql: false
  # Use Flyway only (disable Spring SQL initializer to avoid double-runs)
  sql:
    init:
      mode: never
  flyway:
    enabled: ${SPRING_FLYWAY_ENABLED:true}
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true

logging:
  level:
    org.springframework: INFO
